### ISSUE TITLE
How can I change the output result type to a numeric type?

### ISSUE THREAD

**Issue by wangzhuo0978** [vy/log4j2-logstash-layout#46] opened 2019-10-31 16:12 UTC
now, I can customize the output result through ThreadContext, config 
"resTime": "${json:mdc:resTime}" ,  I get print 
as {"resTime", "1000"},  but for some reason, I just want get {"resTime": 1000}, How could I do;

**Comment by vy** [comment] 2019-11-01 08:54
I am pretty sure `LogstashLayout` handles different object types in MDC. I have modified the `LogstashLayoutTest#test_mdc_key_access()` method as follows to check my assumption:

```java
@Test
public void test_mdc_key_access() {

    // Create the log event.
    SimpleMessage message = new SimpleMessage("Hello, World!");
    StringMap contextData = new SortedArrayStringMap();
    String mdcDirectlyAccessedKey = "mdcKey1";
    int mdcDirectlyAccessedValue = "mdcValue1".hashCode();
    contextData.putValue(mdcDirectlyAccessedKey, mdcDirectlyAccessedValue);
    LogEvent logEvent = Log4jLogEvent
            .newBuilder()
            .setLoggerName(LogstashLayoutTest.class.getSimpleName())
            .setLevel(Level.INFO)
            .setMessage(message)
            .setContextData(contextData)
            .build();

    // Create the event template.
    ObjectNode eventTemplateRootNode = JSON_NODE_FACTORY.objectNode();
    String mdcFieldName = "mdc";
    eventTemplateRootNode.put(mdcFieldName, "${json:mdc}");
    eventTemplateRootNode.put(mdcDirectlyAccessedKey, String.format("${json:mdc:%s}", mdcDirectlyAccessedKey));
    String eventTemplate = eventTemplateRootNode.toString();

    // Create the layout.
    BuiltConfiguration configuration = ConfigurationBuilderFactory.newConfigurationBuilder().build();
    LogstashLayout layout = LogstashLayout
            .newBuilder()
            .setConfiguration(configuration)
            .setStackTraceEnabled(true)
            .setEventTemplate(eventTemplate)
            .build();

    // Check the serialized event.
    System.out.println(layout.toSerializable(logEvent));

}
```

This produces the following output:

```json
{"mdc":{"mdcKey1":-1033093716},"mdcKey1":-1033093716}
```

If you can provide me a setup (e.g., a simple Java project where I can locally run and reproduce the error), I can try helping you out. What you can also do is, put a break point into `ContextDataResolver#resolve(LogEvent, JsonGenerator)` method and trace back how come your MDC does not contain the integer value you were expecting.

**Comment by wangzhuo0978** [comment] 2019-11-01 10:26
Thank you very much for your prompt reply, but I set mdc value via ThreadContext(org.apache.logging.log4j), and I am not sure if there is a better multi-threaded support way than this.  
if use TheadContext,  through the inferface:
```
put(String key, String value)
Puts a context value (the value parameter) as identified with the key parameter into the current thread's context map.
```
I have to set value of type to string ...    If I can explicitly specify the type of a field, it will greatly facilitate the use of the tool.

**Comment by vy** [comment] 2019-11-01 14:44
I will see if we can get it working without introducing a hack into `LogstashLayout`.

**Comment by wangzhuo0978** [comment] 2019-11-02 08:14
This library is very helpful to me, thank you and other contributors. 
```
"${json:mdc:name}"
```
if the user does this, it can be output according to the user-defined data type.

---

my personal thought is
```
"${json:mdc:name:%d}" | "${json:mdc:name:%f}" | "${json:mdc:name:%s}",
```
If this clearly defines the type of name,  can use Long.valueof() or Float.valueOf() or String.valueOf() change the result type. 
For integer types: have, integer, short, bigDecimal, etc.  for efficiency reasons, it is enough to be able to correctly distinguish between long and bigDecimal through  "%?d"

**Comment by vy** [comment] 2019-11-02 20:15
The proposed design makes sense. First I want to make sure that it is indeed impossible to provide non-String values in MDC. See [my post to the log4j-user mailing list](https://lists.apache.org/thread.html/1bb1012553fa4a1f2e116e7dcfae64892a557f40ef34ef33de9e6dff@%3Clog4j-user.logging.apache.org%3E). If `ThreadContext` turns out to be a dead end, I will try sparing some time in 2-3 weeks to push this into a new release.

**Comment by vy** [comment] 2019-11-03 11:46
The log4j-user discussion yielded some useful results. For instance, you can put non-String values into MDC as follows:

1. Set `log4j2.threadContextMap` parameter to `org.apache.logging.log4j.spi.CopyOnWriteSortedArrayThreadContextMap`.

2. Add non-String values into MDC using the `ObjectThreadContextMap` interface:
```java
ObjectThreadContextMap threadContextMap = (ObjectThreadContextMap) ThreadContext.getThreadContextMap();
threadContextMap.putValue("key1", "stringValue");
threadContextMap.putValue("key2", 0xDEADB33F);
```

Is this a practical work around for you, @wangzhuo0978?

**Comment by wangzhuo0978** [comment] 2019-11-03 13:44
Thank you very much for your help, I have not found a way to directly modify log4j2.threadContextMap.   
```
 public static ReadOnlyThreadContextMap getThreadContextMap() {
        return readOnlyContextMap;
    }
```
contextThread does not allow direct modification of threadContextMap, and no set method is provided.  but you have git me some great idea. thanks .

**Comment by wangzhuo0978** [comment] 2019-11-03 15:42
I read the documentation for log4j2 and got the solution.
by
```
System.setProperty("log4j2.threadContextMap", "org.apache.logging.log4j.spi.CopyOnWriteSortedArrayThreadContextMap");
```
able to modify the contextMap, thank you again for your help.

**Comment by vy** [comment] 2019-11-04 12:40
@wangzhuo0978, I am closing the issue. Please do let me know if you have any objections.

**Closed by vy** 2019-11-04 12:40 UTC
